export type VideoTemplate = {
  id: string;
  label: string;
  description: string;
  preview: string;
  bgColor: string;
  transition: string;
  photoDuration: number;
  crossfadeDuration: number;
  introDuration: number;
  outroDuration: number;
  textPosition: "bottom" | "top" | "center";
  textSize: number;
  vignette: boolean;
  kenBurns: boolean;
  borderStyle: "none" | "thin" | "rounded";
  overlayGradient: boolean;
};

export const TEMPLATES: VideoTemplate[] = [
  {
    id: "classique",
    label: "Classique",
    description: "Sobre et digne",
    preview: "#16234c",
    bgColor: "16234c",
    transition: "fade",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 28,
    vignette: false,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: true,
  },
  {
    id: "serenite",
    label: "Sérénité",
    description: "Doux et apaisant",
    preview: "#5b8fb9",
    bgColor: "5b8fb9",
    transition: "fadewhite",
    photoDuration: 6,
    crossfadeDuration: 2,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "center",
    textSize: 30,
    vignette: true,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: false,
  },
  {
    id: "nature",
    label: "Mémoire",
    description: "Tons chauds, rythme apaisé",
    preview: "#2d5016",
    bgColor: "2d5016",
    transition: "fade",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 26,
    vignette: true,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: true,
  },
  {
    id: "cinematique",
    label: "Solennel",
    description: "Recueilli et majestueux",
    preview: "#0a0a0a",
    bgColor: "000000",
    transition: "fadeblack",
    photoDuration: 6,
    crossfadeDuration: 2,
    introDuration: 5,
    outroDuration: 5,
    textPosition: "bottom",
    textSize: 24,
    vignette: false,
    kenBurns: true,
    borderStyle: "none",
    overlayGradient: true,
  },
  {
    id: "lumiere",
    label: "Lumière",
    description: "Lumineux et chaleureux",
    preview: "#8B6914",
    bgColor: "2a1f00",
    transition: "fadewhite",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "top",
    textSize: 26,
    vignette: false,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: false,
  },
  {
    id: "nuit-etoilee",
    label: "Recueillement",
    description: "Intime et respectueux",
    preview: "#0a0a2e",
    bgColor: "0a0a2e",
    transition: "fadeblack",
    photoDuration: 6,
    crossfadeDuration: 2,
    introDuration: 5,
    outroDuration: 5,
    textPosition: "bottom",
    textSize: 28,
    vignette: true,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: true,
  },
  {
    id: "poesie",
    label: "Contemplation",
    description: "Délicat et contemplatif",
    preview: "#6b4c7a",
    bgColor: "6b4c7a",
    transition: "dissolve",
    photoDuration: 7,
    crossfadeDuration: 2.5,
    introDuration: 5,
    outroDuration: 5,
    textPosition: "center",
    textSize: 30,
    vignette: true,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: false,
  },
  {
    id: "ocean",
    label: "Douceur",
    description: "Paisible et serein",
    preview: "#1a4a5e",
    bgColor: "1a4a5e",
    transition: "fade",
    photoDuration: 6,
    crossfadeDuration: 2,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 28,
    vignette: false,
    kenBurns: true,
    borderStyle: "none",
    overlayGradient: true,
  },
  {
    id: "jardin",
    label: "Espérance",
    description: "Lumineux et apaisant",
    preview: "#4a6741",
    bgColor: "2a3d24",
    transition: "fadewhite",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "top",
    textSize: 26,
    vignette: false,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: false,
  },
  {
    id: "automne",
    label: "Souvenir",
    description: "Chaleur des souvenirs",
    preview: "#8B4513",
    bgColor: "3d2208",
    transition: "dissolve",
    photoDuration: 5,
    crossfadeDuration: 2,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 26,
    vignette: true,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: true,
  },
];

export function getTemplate(id: string): VideoTemplate {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}
