export type VideoTemplate = {
  id: string;
  label: string;
  description: string;
  preview: string;         // couleur de prévisualisation pour le wizard
  bgColor: string;         // couleur de fond (hex sans #)
  transition: string;      // type de transition FFmpeg xfade
  photoDuration: number;   // secondes par photo
  crossfadeDuration: number;
  introDuration: number;
  outroDuration: number;
  textPosition: "bottom" | "top" | "center";
  textSize: number;
  vignette: boolean;       // effet vignette sur les photos
  kenBurns: boolean;       // effet zoom lent sur les photos
  borderStyle: "none" | "thin" | "rounded";
  overlayGradient: boolean; // gradient sombre en bas pour lisibilité texte
};

export const TEMPLATES: VideoTemplate[] = [
  {
    id: "classique",
    label: "Classique",
    description: "Sobre et élégant, transitions en fondu",
    preview: "#16234c",
    bgColor: "16234c",
    transition: "fade",
    photoDuration: 4,
    crossfadeDuration: 1,
    introDuration: 3,
    outroDuration: 3,
    textPosition: "bottom",
    textSize: 28,
    vignette: false,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: true,
  },
  {
    id: "serenite",
    label: "Sérénité",
    description: "Doux et apaisant, effet lumineux",
    preview: "#5b8fb9",
    bgColor: "5b8fb9",
    transition: "fadewhite",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "center",
    textSize: 32,
    vignette: true,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: false,
  },
  {
    id: "nature",
    label: "Nature",
    description: "Tons chauds, transitions douces",
    preview: "#2d5016",
    bgColor: "2d5016",
    transition: "smoothleft",
    photoDuration: 4,
    crossfadeDuration: 1,
    introDuration: 3,
    outroDuration: 3,
    textPosition: "bottom",
    textSize: 26,
    vignette: true,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: true,
  },
  {
    id: "cinematique",
    label: "Cinématique",
    description: "Style film, barres noires, zoom lent",
    preview: "#0a0a0a",
    bgColor: "000000",
    transition: "fadeblack",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 24,
    vignette: false,
    kenBurns: true,
    borderStyle: "none",
    overlayGradient: true,
  },
  {
    id: "lumiere",
    label: "Lumière",
    description: "Lumineux et chaleureux, tons dorés",
    preview: "#8B6914",
    bgColor: "2a1f00",
    transition: "fadewhite",
    photoDuration: 4,
    crossfadeDuration: 1.2,
    introDuration: 3,
    outroDuration: 3,
    textPosition: "top",
    textSize: 26,
    vignette: false,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: false,
  },
  {
    id: "nuit-etoilee",
    label: "Nuit étoilée",
    description: "Intime et recueilli, fond sombre",
    preview: "#0a0a2e",
    bgColor: "0a0a2e",
    transition: "slideleft",
    photoDuration: 5,
    crossfadeDuration: 1,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 28,
    vignette: true,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: true,
  },
  {
    id: "poesie",
    label: "Poésie",
    description: "Délicat et raffiné, rythme contemplatif",
    preview: "#6b4c7a",
    bgColor: "6b4c7a",
    transition: "dissolve",
    photoDuration: 6,
    crossfadeDuration: 2,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "center",
    textSize: 30,
    vignette: true,
    kenBurns: false,
    borderStyle: "none",
    overlayGradient: false,
  },
  {
    id: "ocean",
    label: "Océan",
    description: "Calme et profond, comme les vagues",
    preview: "#1a4a5e",
    bgColor: "1a4a5e",
    transition: "smoothright",
    photoDuration: 5,
    crossfadeDuration: 1.5,
    introDuration: 4,
    outroDuration: 4,
    textPosition: "bottom",
    textSize: 28,
    vignette: false,
    kenBurns: true,
    borderStyle: "none",
    overlayGradient: true,
  },
  {
    id: "automne",
    label: "Automne",
    description: "Chaleur des souvenirs, tons ambrés",
    preview: "#8B4513",
    bgColor: "3d2208",
    transition: "wipeleft",
    photoDuration: 4,
    crossfadeDuration: 1,
    introDuration: 3,
    outroDuration: 3,
    textPosition: "bottom",
    textSize: 26,
    vignette: true,
    kenBurns: false,
    borderStyle: "thin",
    overlayGradient: true,
  },
  {
    id: "jardin",
    label: "Jardin secret",
    description: "Paisible et lumineux, douceur florale",
    preview: "#4a6741",
    bgColor: "2a3d24",
    transition: "circlecrop",
    photoDuration: 4,
    crossfadeDuration: 1.2,
    introDuration: 3,
    outroDuration: 3,
    textPosition: "top",
    textSize: 26,
    vignette: false,
    kenBurns: false,
    borderStyle: "rounded",
    overlayGradient: false,
  },
];

export function getTemplate(id: string): VideoTemplate {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}
